# Generated by Django 5.2.11 on 2026-06-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialsession',
            new_name='social_sess_user_id_92da57_idx',
            old_name='social_sess_user_id_4d9e7a_idx',
        ),
        migrations.RenameIndex(
            model_name='socialsession',
            new_name='social_sess_status_9f5906_idx',
            old_name='social_sess_status_832da9_idx',
        ),
    ]
