# Generated by Django 5.2.16 on 2026-08-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sessions', '0002_rename_social_sess_user_id_4d9e7a_idx_social_sess_user_id_92da57_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsession',
            name='status',
            field=models.CharField(choices=[('not_connected', 'Non connecte'), ('connected', 'Connecte'), ('expired', 'Expire'), ('verification_required', 'Verification requise'), ('error', 'Erreur'), ('SESSION_READY', 'Session prete'), ('SESSION_EXPIRED', 'Session expiree'), ('LOGIN_REQUIRED', 'Connexion requise'), ('CHECKPOINT_REQUIRED', 'Checkpoint requis'), ('CAPTCHA_REQUIRED', 'CAPTCHA requis'), ('SESSION_FILE_MISSING', 'Fichier absent'), ('SESSION_FILE_INVALID', 'Fichier invalide'), ('SESSION_HEALTHCHECK_FAILED', 'Health check echoue')], default='not_connected', max_length=30),
        ),
    ]
