# Generated by Django 5.2.11 on 2026-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_team_created_at_remove_team_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('COMMERCIAL', 'Commercial')], default='COMMERCIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('COMMERCIAL', 'Commercial')], default='COMMERCIAL', max_length=20),
        ),
    ]
