# Generated by Django 5.2.11 on 2026-03-30 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0001_initial'),
        ('sales', '0017_pipelinestagetask'),
        ('users', '0008_alter_invitation_role_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.company'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_synced',
            field=models.BooleanField(default=True, help_text='Sync automatique depuis CRM'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='opportunity_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='sales.opportunitypipeline'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='pipeline_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='sales.pipelinealert'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='task_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='sales.taskactivity'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#1976d2', max_length=7),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('task', 'Tâche'), ('meeting', 'Réunion'), ('deadline', 'Échéance Opportunité'), ('reminder', 'Rappel'), ('stage', 'Étape Pipeline'), ('activity', 'Activité CRM'), ('pipeline_alert', 'Alerte Pipeline')], default='task', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['company', 'start'], name='calendar_mo_company_59159b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['assigned_to', 'start'], name='calendar_mo_assigne_0e4e61_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type', 'start'], name='calendar_mo_event_t_e92417_idx'),
        ),
    ]
