sonar.projectKey=viewisecrm-frontend
sonar.projectName=ViewiseCRM Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=\
node_modules/**,\
build/**,\
dist/**,\
coverage/**,\
public/**,\
src_backup/**,\
src_backup_relative_api/**

sonar.javascript.file.suffixes=.none
sonar.css.file.suffixes=.none
sonar.sourceEncoding=UTF-8
