# Generated by Django 5.2.11 on 2026-06-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_supervision_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiagentrun',
            new_name='superadmin__company_17a479_idx',
            old_name='superadmin__company_8ecb1d_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentrun',
            new_name='superadmin__agent_t_78cfd4_idx',
            old_name='superadmin__agent_t_5e6ec1_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentrun',
            new_name='superadmin__status_8e597b_idx',
            old_name='superadmin__status_9bbf1a_idx',
        ),
        migrations.RenameIndex(
            model_name='superadminauditlog',
            new_name='superadmin__company_602b4d_idx',
            old_name='superadmin__company_38c10b_idx',
        ),
        migrations.RenameIndex(
            model_name='superadminauditlog',
            new_name='superadmin__actor_i_37e0b6_idx',
            old_name='superadmin__actor_i_7d0f84_idx',
        ),
        migrations.RenameIndex(
            model_name='superadminauditlog',
            new_name='superadmin__module_f85cf6_idx',
            old_name='superadmin__module_b777f3_idx',
        ),
        migrations.RenameIndex(
            model_name='superadminauditlog',
            new_name='superadmin__action_8cf0f3_idx',
            old_name='superadmin__action_490b77_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthlog',
            new_name='superadmin__service_1c3f68_idx',
            old_name='superadmin__service_86240e_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthlog',
            new_name='superadmin__status_1cc483_idx',
            old_name='superadmin__status_d20abd_idx',
        ),
    ]
