# Generated by Django 5.2.11 on 2026-08-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_audit_ip_and_crm_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemhealthlog',
            name='service',
            field=models.CharField(choices=[('backend', 'Backend'), ('database', 'Database'), ('redis', 'Redis'), ('gemini', 'Gemini')], max_length=40),
        ),
    ]
