# Generated by Codex on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0006_alter_systemhealthlog_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="module",
            field=models.CharField(
                choices=[
                    ("prospects", "Prospects"),
                    ("opportunities", "Opportunités"),
                    ("tasks", "Tâches"),
                    ("contacts", "Contacts"),
                    ("accounts", "Comptes"),
                    ("campaigns", "Campagnes"),
                    ("profile", "Profil"),
                    ("engagement", "Agent d'engagement"),
                    ("qualification", "Agent de qualification"),
                    ("agent_crm", "Agent CRM"),
                    ("superadmin", "Super Admin"),
                    ("dashboard", "Dashboard"),
                    ("other", "Autre"),
                ],
                max_length=30,
            ),
        ),
    ]
