# Generated by Django 5.2.11 on 2026-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscriptionplan_is_trial_and_more'),
        ('users', '0003_user_company_alter_company_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysubscription',
            old_name='trial_end',
            new_name='cancelled_at',
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='last_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['end_date', 'is_active'], name='subscriptio_end_dat_c80387_idx'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['trial_end_date', 'is_trial'], name='subscriptio_trial_e_0a3994_idx'),
        ),
    ]
