# Generated by Django 5.2.11 on 2026-03-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_trial_end_companysubscription_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
