# Generated by Django 5.2.11 on 2026-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_companysubscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
