# Generated by Django 5.2.11 on 2026-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_companysubscription_stripe_checkout_session_id'),
        ('users', '0008_alter_invitation_role_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscription',
            name='stripe_checkout_session_id',
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__373499_idx'),
        ),
    ]
