# Generated by Django 6.1 on 2026-08-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentQualification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prospectqualification',
            new_name='agentQualif_prospec_b8aaee_idx',
            old_name='agentQuali_prospec_1b36f4_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectqualification',
            new_name='agentQualif_status_0636fb_idx',
            old_name='agentQuali_status_9edc03_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectqualification',
            new_name='agentQualif_qualifi_1cf017_idx',
            old_name='agentQuali_qualifi_0ded65_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectqualification',
            new_name='agentQualif_opportu_2ab6f0_idx',
            old_name='agentQuali_opportu_f19d27_idx',
        ),
    ]
