# Generated by Django 5.2.11 on 2026-03-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_invitation_role_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('assign', 'Assignation'), ('unassign', 'Désassignation'), ('status', 'Changement de statut'), ('stage', "Changement d'étape"), ('comment', 'Commentaire'), ('invite', 'Invitation')], max_length=20)),
                ('entity_type', models.CharField(choices=[('prospect', 'Prospect'), ('contact', 'Contact'), ('opportunity', 'Opportunité'), ('task', 'Tâche'), ('activity', 'Activité'), ('user', 'Utilisateur'), ('team', 'Équipe'), ('company', 'Entreprise')], max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, help_text="Nom lisible de l'entité au moment de l'action", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Détail humain de ce qui a changé')),
                ('old_value', models.JSONField(blank=True, help_text='Valeurs avant modification', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Valeurs après modification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL, verbose_name="Auteur de l'action")),
                ('affected_users', models.ManyToManyField(blank=True, related_name='history_concerned', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs concernés')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='users.company')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notif_type', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20)),
                ('entity_type', models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('contact', 'Contact'), ('opportunity', 'Opportunité'), ('task', 'Tâche'), ('activity', 'Activité'), ('user', 'Utilisateur'), ('team', 'Équipe'), ('company', 'Entreprise')], max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Notifications.historylog')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
