# Generated by Django 6.1 on 2026-08-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_backfill_historylog_actor_names'),
        ('sales', '0043_prospectagentrun_prospectactivity_prospectdocument_and_more'),
        ('users', '0008_alter_invitation_role_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('prospect_created', 'Prospect créé'), ('prospect_enriched', 'Prospect enrichi'), ('prospect_qualified', 'Prospect qualifié'), ('prospect_status_changed', 'Statut prospect modifié'), ('commercial_activity_created', 'Activité commerciale ajoutée'), ('call_completed', 'Appel effectué'), ('message_generated', 'Message généré'), ('message_sent', 'Message envoyé'), ('reply_received', 'Réponse reçue'), ('prospect_interested', 'Prospect intéressé'), ('document_uploaded', 'Document ajouté'), ('score_changed', 'Score recalculé'), ('opportunity_created', 'Opportunité créée'), ('opportunity_status_changed', 'Statut opportunité modifié'), ('opportunity_won', 'Opportunité gagnée'), ('opportunity_lost', 'Opportunité perdue'), ('agent_started', 'Agent lancé'), ('agent_completed', 'Agent terminé'), ('agent_failed', 'Agent échoué'), ('recommendation_created', 'Recommandation créée'), ('recommendation_completed', 'Recommandation réalisée')], max_length=60)),
                ('category', models.CharField(choices=[('prospect', 'Prospect'), ('commercial', 'Commercial'), ('engagement', 'Engagement'), ('agent', 'Agent IA'), ('scoring', 'Scoring'), ('document', 'Document'), ('opportunity', 'Opportunité'), ('task', 'Tâche'), ('system', 'Système')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('critical', 'Critique')], db_index=True, default='info', max_length=20)),
                ('source_type', models.CharField(choices=[('manual', 'Manuel'), ('agent', 'Agent'), ('system', 'Système'), ('prospect_activity', 'Activité prospect'), ('score_history', 'Historique score'), ('prospect_document', 'Document prospect'), ('prospect_agent_run', 'Exécution agent prospect'), ('engagement_log', 'Engagement'), ('opportunity', 'Opportunité')], default='system', max_length=40)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('related_object_type', models.CharField(blank=True, max_length=80)),
                ('related_object_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('channel', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_events', to='sales.prospectagentrun')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_events', to='users.company')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_events', to='sales.prospect')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement CRM',
                'verbose_name_plural': 'Événements CRM',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='Notificatio_company_b940b3_idx'), models.Index(fields=['event_type', '-created_at'], name='Notificatio_event_t_0b0357_idx'), models.Index(fields=['category', '-created_at'], name='Notificatio_categor_733dd8_idx'), models.Index(fields=['prospect', '-created_at'], name='Notificatio_prospec_af3723_idx'), models.Index(fields=['user', '-created_at'], name='Notificatio_user_id_ca13e1_idx'), models.Index(fields=['severity', '-created_at'], name='Notificatio_severit_6c7b78_idx'), models.Index(fields=['source_type', 'source_id', 'event_type'], name='Notificatio_source__6e5898_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id__gt', '')), fields=('event_type', 'source_type', 'source_id'), name='unique_crm_event_source')],
            },
        ),
    ]
