# Generated by Django 5.2.11 on 2026-06-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentEngagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='engagementcampaign',
            new_name='agentEngage_company_9af815_idx',
            old_name='agentEngag_company_58f518_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='agentEngage_company_557d71_idx',
            old_name='agentEngag_company_20d0ad_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='agentEngage_prospec_6ec050_idx',
            old_name='agentEngag_prospec_eb1c1f_idx',
        ),
    ]
