# Generated by Django 6.1 on 2026-08-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentEngagement', '0005_prospectengagementmemory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prospectengagementmemory',
            new_name='agentEngage_prospec_92c6c7_idx',
            old_name='agentEngag_prospec_071b74_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectengagementmemory',
            new_name='agentEngage_interes_2fe789_idx',
            old_name='agentEngag_interes_2ea99b_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectengagementmemory',
            new_name='agentEngage_next_di_2a1b6c_idx',
            old_name='agentEngag_next_di_f168f8_idx',
        ),
    ]
