# Generated by Django 6.1 on 2026-08-28 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentEngagement', '0006_rename_agentengag_prospec_071b74_idx_agentengage_prospec_92c6c7_idx_and_more'),
        ('sales', '0043_prospectagentrun_prospectactivity_prospectdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('INITIAL_ENGAGEMENT', 'Engagement initial'), ('CONTINUE_AFTER_INTERACTION', 'Continuation après interaction'), ('REPLAN', 'Replanification')], max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('COMPLETED', 'Terminé'), ('MANUAL_REVIEW', 'Vérification requise'), ('FAILED', 'Échec')], default='RUNNING', max_length=30)),
                ('content_generation_allowed', models.BooleanField(default=True)),
                ('manual_review_required', models.BooleanField(default=False)),
                ('manual_review_reason', models.TextField(blank=True, null=True)),
                ('final_strategy', models.CharField(blank=True, max_length=80, null=True)),
                ('final_objective', models.CharField(blank=True, max_length=80, null=True)),
                ('final_channel', models.CharField(blank=True, max_length=40, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=40, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_agent_runs', to='sales.prospect')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementAgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=80)),
                ('reason', models.TextField(blank=True, default='')),
                ('observation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agentEngagement.engagementagentrun')),
            ],
            options={
                'ordering': ['step_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='engagementagentrun',
            index=models.Index(fields=['prospect', 'started_at'], name='agentEngage_prospec_e14e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementagentrun',
            index=models.Index(fields=['user', 'started_at'], name='agentEngage_user_id_437a71_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementagentrun',
            index=models.Index(fields=['status', 'started_at'], name='agentEngage_status_124425_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementagentrun',
            index=models.Index(fields=['goal', 'started_at'], name='agentEngage_goal_5071b1_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementagentstep',
            index=models.Index(fields=['run', 'step_number'], name='agentEngage_run_id_1c29e6_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementagentstep',
            index=models.Index(fields=['action', 'created_at'], name='agentEngage_action_268f64_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagementagentstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_number'), name='unique_engagement_agent_run_step'),
        ),
    ]
