# Generated by Django 5.2.11 on 2026-03-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_prospect_evaluation_prospect_mobile_prospect_origin_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospectcompany',
            unique_together={('name', 'company')},
        ),
    ]
