# Generated by Django 5.2.11 on 2026-03-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sales.account'),
        ),
    ]
