# Generated by Django 5.2.11 on 2026-03-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_contact_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='sales.contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='sales.prospect'),
        ),
    ]
