# Generated by Django 5.2.11 on 2026-03-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_opportunity_contact_alter_opportunity_prospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='secondary_email',
        ),
    ]
