# Generated by Django 5.2.11 on 2026-03-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_prospect_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='skype_id',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='prospectcompany',
            name='address',
        ),
        migrations.RemoveField(
            model_name='prospectcompany',
            name='website',
        ),
    ]
