# Generated by Django 5.2.11 on 2026-03-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_account_address_remove_account_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
    ]
