# Generated by Django 5.2.11 on 2026-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quota_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='quota_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('classic', 'Tâche classique'), ('quota', 'Tâche quota / objectif')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
