# Generated by Django 5.2.11 on 2026-03-17 20:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_taskactivity_taskcomment_alter_task_options_and_more'),
        ('users', '0008_alter_invitation_role_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.company')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback manager',
                'verbose_name_plural': 'Feedbacks manager',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('top_seller', 'Top vendeur du mois'), ('on_time_100', 'Respect des délais 100%'), ('best_closer', 'Meilleur closing'), ('calls_100', '100 appels ce mois'), ('email_champion', 'Email champion'), ('streak_3', '3 mois consécutifs top'), ('most_improved', 'Plus grande progression')], max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.company')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-awarded_at'],
                'unique_together': {('commercial', 'badge_type', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('prospects_contacted', 'Prospects contactés'), ('opportunities_won', 'Opportunités gagnées'), ('calls', 'Appels effectués'), ('emails', 'Emails envoyés'), ('meetings', 'Meetings réalisés'), ('tasks_done', 'Tâches terminées')], max_length=30)),
                ('target_value', models.PositiveIntegerField()),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('active', 'En cours'), ('achieved', 'Atteint'), ('failed', 'Échoué')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='users.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objectif de performance',
                'verbose_name_plural': 'Objectifs de performance',
                'ordering': ['-year', '-month', 'goal_type'],
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='sales_perfo_company_bcccf4_idx'), models.Index(fields=['commercial', 'year', 'month'], name='sales_perfo_commerc_08b80a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tasks_total', models.PositiveIntegerField(default=0)),
                ('tasks_done', models.PositiveIntegerField(default=0)),
                ('tasks_on_time', models.PositiveIntegerField(default=0)),
                ('tasks_late', models.PositiveIntegerField(default=0)),
                ('calls_count', models.PositiveIntegerField(default=0)),
                ('emails_count', models.PositiveIntegerField(default=0)),
                ('meetings_count', models.PositiveIntegerField(default=0)),
                ('opportunities_won', models.PositiveIntegerField(default=0)),
                ('opportunities_total', models.PositiveIntegerField(default=0)),
                ('penalty_points', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='users.company')),
            ],
            options={
                'verbose_name': 'Score de performance',
                'verbose_name_plural': 'Scores de performance',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='sales_perfo_company_30bc0c_idx'), models.Index(fields=['commercial', 'year', 'month'], name='sales_perfo_commerc_7ca71b_idx')],
                'unique_together': {('commercial', 'year', 'month')},
            },
        ),
    ]
