# Generated by Django 5.2.11 on 2026-03-23 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_contact_assigned_to'),
        ('users', '0008_alter_invitation_role_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pipeline_type', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('custom', 'Personnalisé')], default='b2b', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('delayed', 'Delayed'), ('blocked', 'Blocked'), ('won', 'Won'), ('lost', 'Lost')], default='on_track', max_length=20)),
                ('progression', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_pipelines', to='users.company')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_data', to='sales.opportunity')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='sales.pipeline')),
            ],
            options={
                'verbose_name': 'Opportunité Pipeline',
                'verbose_name_plural': 'Opportunités Pipeline',
            },
        ),
        migrations.CreateModel(
            name='PipelineAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('stage_overdue', 'Étape en retard'), ('no_activity', 'Aucune activité'), ('tasks_pending', 'Tâches en attente'), ('at_risk', 'Opportunité à risque'), ('blocked', 'Opportunité bloquée')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_alerts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_alerts', to='users.company')),
                ('opportunity_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sales.opportunitypipeline')),
            ],
            options={
                'verbose_name': 'Alerte Pipeline',
                'verbose_name_plural': 'Alertes Pipeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('max_duration_days', models.PositiveIntegerField(default=7, help_text='Durée max en jours avant alerte')),
                ('warning_threshold_pct', models.PositiveIntegerField(default=80, help_text='% du temps écoulé avant alerte orange')),
                ('color', models.CharField(choices=[('blue', '#3B82F6'), ('green', '#10B981'), ('yellow', '#F59E0B'), ('orange', '#F97316'), ('red', '#EF4444'), ('purple', '#8B5CF6'), ('pink', '#EC4899'), ('gray', '#6B7280')], default='blue', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='users.company')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sales.pipeline')),
            ],
            options={
                'verbose_name': 'Étape du pipeline',
                'verbose_name_plural': 'Étapes du pipeline',
                'ordering': ['pipeline', 'order'],
                'unique_together': {('pipeline', 'order')},
            },
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_opportunities', to='sales.pipelinestage'),
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entered', "Entrée dans l'étape"), ('exited', "Sortie de l'étape"), ('moved_forward', 'Avancement'), ('moved_backward', 'Retour'), ('won', 'Gagné'), ('lost', 'Perdu'), ('note', 'Note ajoutée'), ('task_completed', 'Tâche complétée'), ('alert', 'Alerte générée')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('duration_in_stage_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_histories', to='users.company')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='sales.pipelinestage')),
                ('opportunity_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales.opportunitypipeline')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='sales.pipelinestage')),
            ],
            options={
                'verbose_name': "Historique d'étape",
                'verbose_name_plural': "Historiques d'étapes",
                'ordering': ['-created_at'],
            },
        ),
    ]
