# Generated by Django 5.2.11 on 2026-03-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_pipeline_opportunitypipeline_pipelinealert_and_more'),
        ('users', '0008_alter_invitation_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_days_after_entry', models.PositiveIntegerField(default=2, help_text='Délai en jours pour la due_date de la tâche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stage_tasks', to='users.company')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='sales.pipelinestage')),
            ],
            options={
                'verbose_name': 'Template de tâche pipeline',
                'verbose_name_plural': 'Templates de tâches pipeline',
                'ordering': ['stage', 'order'],
            },
        ),
    ]
