# Generated by Django 5.2.11 on 2026-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_contact_city_contact_country_prospect_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestagetask',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Appel'), ('email', 'Email'), ('meeting', 'Réunion'), ('document', 'Document'), ('research', 'Recherche'), ('note', 'Note'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
