# Generated by Django 5.2.11 on 2026-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_pipelinestagetask_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='crm_stage',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('qualified', 'Qualifiée'), ('proposal', 'Proposition'), ('negotiation', 'Négociation'), ('won', 'Gagnée'), ('lost', 'Perdue'), ('none', 'Aucun (étape personnalisée)')], default='none', help_text='Stage CRM correspondant à cette étape pipeline', max_length=20),
        ),
    ]
