# Generated by Django 5.2.11 on 2026-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_pipelinestage_crm_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='raison_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='evaluation',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='next_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='osm_place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='score_ia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='source',
            field=models.CharField(default='agent_prospection', max_length=50),
        ),
        migrations.AddField(
            model_name='prospectcompany',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
