# Generated by Django 5.2.11 on 2026-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_prospect_source_prospect_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='engagement_status',
            field=models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('task_created', 'Task Created'), ('message_ready', 'Message Ready'), ('contacted', 'Contacted'), ('waiting_reply', 'Waiting Reply'), ('failed', 'Failed')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='generated_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_engagement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_engagement_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
