# Generated by Django 5.2.11 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_prospect_engagement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='engagement_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='engagement_status',
            field=models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('task_created', 'Task Created'), ('message_ready', 'Message Ready'), ('contacted', 'Contacted'), ('waiting_reply', 'Waiting Reply'), ('failed', 'Failed'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], default='new', max_length=30),
        ),
    ]
