# Generated by Django 5.2.11 on 2026-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_prospect_engagement_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='engagement_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='engagement_status',
            field=models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('task_created', 'Task Created'), ('message_ready', 'Message Ready'), ('contacted', 'Contacted'), ('waiting_reply', 'Waiting Reply'), ('failed', 'Failed')], default='new', max_length=30),
        ),
    ]
