# Generated by Django 5.2.11 on 2026-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_prospect_optional_company_and_source_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='engagement_status',
            field=models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('message_ready', 'Message Ready'), ('sending', 'Sending'), ('message_sent', 'Message Sent'), ('message_failed', 'Message Failed'), ('replied', 'Replied'), ('follow_up_required', 'Follow-up Required'), ('closed', 'Closed'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('task_created', 'Task Created'), ('contacted', 'Contacted'), ('waiting_reply', 'Waiting Reply'), ('failed', 'Failed')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source',
            field=models.CharField(choices=[('commercial', 'Ajouté par un commercial'), ('agent_prospection', 'Agent de prospection'), ('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('web', 'Web'), ('other', 'Autre')], default='commercial', max_length=50),
        ),
        migrations.AlterField(
            model_name='prospectcompany',
            name='source',
            field=models.CharField(choices=[('commercial', 'Ajouté par un commercial'), ('agent_prospection', 'Agent de prospection'), ('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('web', 'Web'), ('other', 'Autre')], default='commercial', max_length=50),
        ),
    ]
