# Generated by Django 5.2.11 on 2026-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_prospect_engagement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_hook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_last_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_relevance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_profile_tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
