# Generated by Django 5.2.11 on 2026-06-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_prospect_description_and_more'),
        ('sales', '0032_prospect_social_profile_description_topics'),
    ]

    operations = [
    ]
