# Generated by Django 5.2.11 on 2026-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_prospectcompany_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='analysis_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='profile_analysis_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
