# Generated by Django 5.2.11 on 2026-08-24 10:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_discovery_sources'),
        ('superadmin', '0005_audit_ip_and_crm_agent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('discovery', 'Discovery Agent'), ('enrichment', 'Enrichment Agent'), ('qualification', 'Qualification Agent'), ('engagement', 'Engagement Agent'), ('crm', 'CRM Agent'), ('other', 'Autre')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_summary', models.TextField(blank=True, null=True)),
                ('output_summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_360_runs', to='superadmin.aiagentrun')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='sales.prospect')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call_done', 'Appel effectué'), ('email_sent', 'Email envoyé'), ('message_sent', 'Message envoyé'), ('reply_received', 'Réponse reçue'), ('interaction_detected', 'Interaction détectée'), ('interested', 'Prospect intéressé'), ('not_interested', 'Prospect non intéressé'), ('info_requested', "Demande d'informations"), ('meeting_scheduled', 'Réunion planifiée'), ('meeting_done', 'Réunion réalisée'), ('follow_up', 'Relance'), ('no_response', 'Aucun retour'), ('commercial_note', 'Note commerciale'), ('other', 'Autre')], max_length=40)),
                ('channel', models.CharField(blank=True, choices=[('phone', 'Téléphone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('meeting', 'Réunion'), ('website', 'Site web'), ('other', 'Autre')], max_length=30, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('agent', 'Agent'), ('system', 'System')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_activities', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_activities', to='sales.prospect')),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='sales.prospectagentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('presentation', 'Présentation'), ('quote', 'Devis'), ('contract', 'Contrat'), ('proposal', 'Proposition commerciale'), ('specifications', 'Cahier des charges'), ('report', 'Rapport'), ('attachment', 'Pièce jointe'), ('other', 'Autre')], default='attachment', max_length=30)),
                ('file', models.FileField(upload_to='prospect_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'txt'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('agent', 'Agent'), ('system', 'System')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.prospectagentrun')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.prospect')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('send_presentation', 'Envoyer une présentation'), ('follow_up', 'Relancer'), ('schedule_meeting', 'Planifier une réunion'), ('create_opportunity', 'Créer une opportunité'), ('qualify', 'Qualifier'), ('other', 'Autre')], default='follow_up', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('generated_by', models.CharField(choices=[('manual', 'Manual'), ('agent', 'Agent'), ('system', 'System')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='sales.prospectagentrun')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='sales.prospect')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('new_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_changes', to='sales.prospectactivity')),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_changes', to='sales.prospectagentrun')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='sales.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prospectagentrun',
            index=models.Index(fields=['prospect', 'started_at'], name='sales_prosp_prospec_929721_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectagentrun',
            index=models.Index(fields=['agent_type', 'status'], name='sales_prosp_agent_t_d47add_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectactivity',
            index=models.Index(fields=['prospect', 'created_at'], name='sales_prosp_prospec_ee0fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectactivity',
            index=models.Index(fields=['activity_type', 'source'], name='sales_prosp_activit_17e9de_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectdocument',
            index=models.Index(fields=['prospect', 'created_at'], name='sales_prosp_prospec_6dd7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectrecommendation',
            index=models.Index(fields=['prospect', 'status'], name='sales_prosp_prospec_8ddd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectrecommendation',
            index=models.Index(fields=['priority', 'created_at'], name='sales_prosp_priorit_1f8f26_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectscorehistory',
            index=models.Index(fields=['prospect', 'created_at'], name='sales_prosp_prospec_e9ab82_idx'),
        ),
    ]
